apiVersion: v1
kind: Service
metadata:
  name: shift-sched-loadbalancer
spec:
  selector:
    app: shift-sched
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer