apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: pvc-shift-scheduler
spec: 
  storageClassName: linode-block-storage-retain 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 200Mi 
